# - pre-commit run --all-files

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: ^(docs_page/|README.md)
    -   id: trailing-whitespace
        exclude: ^(docs_page/|README.md)
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: ^(docs_page/|README.md)
